/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import {
  useGLTF,
  PerspectiveCamera,
  useAnimations,
  PositionalAudio,
} from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Default003-st_leather004"]: THREE.Mesh;
    ["Default003-black_st002"]: THREE.Mesh;
    ["Sketchfab_model004-Glossy003"]: THREE.Mesh;
    ["Sketchfab_model004-Door"]: THREE.Mesh;
    strelka_mi_1: THREE.Mesh;
    ["strelka_mi-m1002"]: THREE.Mesh;
    ["strelka_mi-white_st002"]: THREE.Mesh;
    ["strelka_mi-st_gold002"]: THREE.Mesh;
    ["Fan_Light1-Mat_win"]: THREE.Mesh;
    ["Fan_Light1-m1002"]: THREE.Mesh;
    ["Fan_Light1-st_tile"]: THREE.Mesh;
    ["Group07-box"]: THREE.Mesh;
    ["Group07-box_corp"]: THREE.Mesh;
    ["Group07-st_wood"]: THREE.Mesh;
    ["Default-st_leather004"]: THREE.Mesh;
    ["Default-black_st002"]: THREE.Mesh;
    ["Default001-st_leather004"]: THREE.Mesh;
    ["Default001-black_st002"]: THREE.Mesh;
    ["Default002-st_leather004"]: THREE.Mesh;
    ["Default002-black_st002"]: THREE.Mesh;
    ["Sketchfab_model001-material"]: THREE.Mesh;
    ["Sketchfab_model001-Mat"]: THREE.Mesh;
    ["Sketchfab_model001-Leaf"]: THREE.Mesh;
    ["Sketchfab_model001-Dirt"]: THREE.Mesh;
    ["Sketchfab_model003-material"]: THREE.Mesh;
    ["Sketchfab_model003-Mat"]: THREE.Mesh;
    ["Sketchfab_model003-Leaf"]: THREE.Mesh;
    ["Sketchfab_model003-Dirt"]: THREE.Mesh;
    ["Sketchfab_model002-material"]: THREE.Mesh;
    ["Sketchfab_model002-Mat"]: THREE.Mesh;
    ["Sketchfab_model002-Leaf"]: THREE.Mesh;
    ["Sketchfab_model002-Dirt"]: THREE.Mesh;
    ["Sketchfab_model005-Metal1"]: THREE.Mesh;
    ["Sketchfab_model005-material003"]: THREE.Mesh;
    ["Sketchfab_model005-metal1"]: THREE.Mesh;
    ["Sketchfab_model005-Base"]: THREE.Mesh;
    ["Sketchfab_model005-SIGN"]: THREE.Mesh;
    Plane005: THREE.Mesh;
    Object_2: THREE.Mesh;
    Cylinder_DefaultMaterial_0: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane001: THREE.Mesh;
    Fan_Light_: THREE.Mesh;
    Sketchfab_model006: THREE.Mesh;
  };
  materials: {
    ["st_leather.004"]: THREE.MeshStandardMaterial;
    ["black_st.002"]: THREE.MeshStandardMaterial;
    ["Glossy.003"]: THREE.MeshStandardMaterial;
    Door: THREE.MeshStandardMaterial;
    ["m1.002"]: THREE.MeshStandardMaterial;
    ["white_st.002"]: THREE.MeshStandardMaterial;
    ["st_gold.002"]: THREE.MeshStandardMaterial;
    Mat_win: THREE.MeshStandardMaterial;
    st_tile: THREE.MeshStandardMaterial;
    box: THREE.MeshStandardMaterial;
    ["box corp"]: THREE.MeshStandardMaterial;
    ["st wood"]: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Mat: THREE.MeshStandardMaterial;
    Leaf: THREE.MeshStandardMaterial;
    Dirt: THREE.MeshStandardMaterial;
    Metal1: THREE.MeshStandardMaterial;
    ["material.003"]: THREE.MeshStandardMaterial;
    metal1: THREE.MeshStandardMaterial;
    Base: THREE.MeshStandardMaterial;
    SIGN: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    DefaultMaterial: THREE.MeshStandardMaterial;
    Painted_Concrete_ulxedaag: THREE.MeshStandardMaterial;
    ["Seychelles_Beige_Marble_wgildfbv.1"]: THREE.MeshStandardMaterial;
    Material__25: THREE.MeshStandardMaterial;
  };
};

type ActionName = "animation_0";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Jpbs(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/jpbs/jpbs.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.animation_0?.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group
          name="Default003"
          position={[616.18, -582.89, -695.81]}
          rotation={[0, -1.53, 0]}
          scale={2.53}
        >
          <mesh
            name="Default003-st_leather004"
            geometry={nodes["Default003-st_leather004"].geometry}
            material={materials["st_leather.004"]}
            castShadow
          />
          <mesh
            name="Default003-black_st002"
            geometry={nodes["Default003-black_st002"].geometry}
            material={materials["black_st.002"]}
            castShadow
          />
        </group>
        <group name="Sketchfab_model004" position={[-901.52, -417.1, -677.7]}>
          <mesh
            name="Sketchfab_model004-Glossy003"
            geometry={nodes["Sketchfab_model004-Glossy003"].geometry}
            material={materials["Glossy.003"]}
            castShadow
          />
          <mesh
            name="Sketchfab_model004-Door"
            geometry={nodes["Sketchfab_model004-Door"].geometry}
            material={materials.Door}
            castShadow
          />
        </group>
        <group
          name="strelka_mi"
          position={[898.12, 169.99, -672.71]}
          rotation={[0, -1.57, 0]}
          scale={0.03}
        >
          <mesh
            name="strelka_mi_1"
            geometry={nodes.strelka_mi_1.geometry}
            material={nodes.strelka_mi_1.material}
            castShadow
          />
          <mesh
            name="strelka_mi-m1002"
            geometry={nodes["strelka_mi-m1002"].geometry}
            material={materials["m1.002"]}
            castShadow
          />
          <mesh
            name="strelka_mi-white_st002"
            geometry={nodes["strelka_mi-white_st002"].geometry}
            material={materials["white_st.002"]}
            castShadow
          />
          <mesh
            name="strelka_mi-st_gold002"
            geometry={nodes["strelka_mi-st_gold002"].geometry}
            material={materials["st_gold.002"]}
            castShadow
          />
        </group>
        <group name="Fan_Light1" position={[0, 486.39, -757.63]} scale={10.31}>
          <mesh
            name="Fan_Light1-Mat_win"
            geometry={nodes["Fan_Light1-Mat_win"].geometry}
            material={materials.Mat_win}
            castShadow
          />
          <mesh
            name="Fan_Light1-m1002"
            geometry={nodes["Fan_Light1-m1002"].geometry}
            material={materials["m1.002"]}
            castShadow
          />
          <mesh
            name="Fan_Light1-st_tile"
            geometry={nodes["Fan_Light1-st_tile"].geometry}
            material={materials.st_tile}
            castShadow
          />
        </group>
        <group
          name="Group07"
          position={[-443.35, -440.84, -251.56]}
          rotation={[0, -1.57, 0]}
          scale={3.03}
        >
          <mesh
            name="Group07-box"
            geometry={nodes["Group07-box"].geometry}
            material={materials.box}
            castShadow
          />
          <mesh
            name="Group07-box_corp"
            geometry={nodes["Group07-box_corp"].geometry}
            material={materials["box corp"]}
            castShadow
          />
          <mesh
            name="Group07-st_wood"
            geometry={nodes["Group07-st_wood"].geometry}
            material={materials["st wood"]}
            castShadow
          />
        </group>
        <group name="Default" position={[-658, -603.21, -1154.25]} scale={2.53}>
          <mesh
            name="Default-st_leather004"
            geometry={nodes["Default-st_leather004"].geometry}
            material={materials["st_leather.004"]}
            castShadow
          />
          <mesh
            name="Default-black_st002"
            geometry={nodes["Default-black_st002"].geometry}
            material={materials["black_st.002"]}
            castShadow
          />
        </group>
        <group
          name="Default001"
          position={[-516.74, -603.21, -1154.25]}
          scale={2.53}
        >
          <mesh
            name="Default001-st_leather004"
            geometry={nodes["Default001-st_leather004"].geometry}
            material={materials["st_leather.004"]}
            castShadow
          />
          <mesh
            name="Default001-black_st002"
            geometry={nodes["Default001-black_st002"].geometry}
            material={materials["black_st.002"]}
            castShadow
          />
        </group>
        <group
          name="Default002"
          position={[-785.12, -603.21, -952.08]}
          rotation={[Math.PI, 1.5, -Math.PI]}
          scale={2.53}
        >
          <mesh
            name="Default002-st_leather004"
            geometry={nodes["Default002-st_leather004"].geometry}
            material={materials["st_leather.004"]}
            castShadow
          />
          <mesh
            name="Default002-black_st002"
            geometry={nodes["Default002-black_st002"].geometry}
            material={materials["black_st.002"]}
            castShadow
          />
        </group>
        <group name="Sketchfab_model001" position={[-740.29, -573, -185.11]}>
          <mesh
            name="Sketchfab_model001-material"
            geometry={nodes["Sketchfab_model001-material"].geometry}
            material={materials.material}
          />
          <mesh
            name="Sketchfab_model001-Mat"
            geometry={nodes["Sketchfab_model001-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            name="Sketchfab_model001-Leaf"
            geometry={nodes["Sketchfab_model001-Leaf"].geometry}
            material={materials.Leaf}
          />
          <mesh
            name="Sketchfab_model001-Dirt"
            geometry={nodes["Sketchfab_model001-Dirt"].geometry}
            material={materials.Dirt}
          />
        </group>
        <group name="Sketchfab_model003" position={[792.5, -573, -1138.46]}>
          <mesh
            name="Sketchfab_model003-material"
            geometry={nodes["Sketchfab_model003-material"].geometry}
            material={materials.material}
          />
          <mesh
            name="Sketchfab_model003-Mat"
            geometry={nodes["Sketchfab_model003-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            name="Sketchfab_model003-Leaf"
            geometry={nodes["Sketchfab_model003-Leaf"].geometry}
            material={materials.Leaf}
          />
          <mesh
            name="Sketchfab_model003-Dirt"
            geometry={nodes["Sketchfab_model003-Dirt"].geometry}
            material={materials.Dirt}
          />
        </group>
        <group name="Sketchfab_model002" position={[748.08, -573, -157.32]}>
          <mesh
            name="Sketchfab_model002-material"
            geometry={nodes["Sketchfab_model002-material"].geometry}
            material={materials.material}
          />
          <mesh
            name="Sketchfab_model002-Mat"
            geometry={nodes["Sketchfab_model002-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            name="Sketchfab_model002-Leaf"
            geometry={nodes["Sketchfab_model002-Leaf"].geometry}
            material={materials.Leaf}
          />
          <mesh
            name="Sketchfab_model002-Dirt"
            geometry={nodes["Sketchfab_model002-Dirt"].geometry}
            material={materials.Dirt}
          />
        </group>
        <group name="Sketchfab_model005" position={[-883.13, 125.55, -670.83]}>
          <mesh
            name="Sketchfab_model005-Metal1"
            geometry={nodes["Sketchfab_model005-Metal1"].geometry}
            material={materials.Metal1}
            castShadow
          />
          <mesh
            name="Sketchfab_model005-material003"
            geometry={nodes["Sketchfab_model005-material003"].geometry}
            material={materials["material.003"]}
            castShadow
          />
          <mesh
            name="Sketchfab_model005-metal1"
            geometry={nodes["Sketchfab_model005-metal1"].geometry}
            material={materials.metal1}
            castShadow
          />
          <mesh
            name="Sketchfab_model005-Base"
            geometry={nodes["Sketchfab_model005-Base"].geometry}
            material={materials.Base}
            castShadow
          />
          <mesh
            name="Sketchfab_model005-SIGN"
            geometry={nodes["Sketchfab_model005-SIGN"].geometry}
            material={materials.SIGN}
            castShadow
          />
        </group>
        <PerspectiveCamera
          name="Camera"
          makeDefault={false}
          far={10000000000}
          near={0.01}
          fov={22.9}
          position={[4080.87, 2593.29, 113.97]}
          rotation={[-1.29, 0.97, 1.23]}
        />
        <mesh
          name="Plane005"
          geometry={nodes.Plane005.geometry}
          material={materials["Material.001"]}
          position={[-294.31, -316.43, -286.65]}
          rotation={[-1.16, 1.19, 1.13]}
          scale={21.64}
        ></mesh>
        <mesh
          name="Object_2"
          geometry={nodes.Object_2.geometry}
          material={materials["white_st.002"]}
          position={[-165.09, -155.34, -371.98]}
        />
        <mesh
          name="Cylinder_DefaultMaterial_0"
          geometry={nodes.Cylinder_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-503.94, -571.99, -286.63]}
          castShadow
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials.Painted_Concrete_ulxedaag}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1000, 50, 600]}
          material-metalness={1}
          receiveShadow
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={materials.Painted_Concrete_ulxedaag}
          position={[-949.98, 0, -649.98]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[600, 50, 600]}
          receiveShadow
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={materials.Painted_Concrete_ulxedaag}
          position={[0, 0, -1299.94]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1000, 50, 600]}
          receiveShadow
        />
        <mesh
          name="Cube004"
          geometry={nodes.Cube004.geometry}
          material={materials.Painted_Concrete_ulxedaag}
          position={[950.03, 0, -649.98]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[600, 50, 600]}
          receiveShadow
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Seychelles_Beige_Marble_wgildfbv.1"]}
          position={[0, -597.01, -650.26]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1000, 600, 100]}
          receiveShadow
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials.Painted_Concrete_ulxedaag}
          position={[0, 572.9, -650.26]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1000, 600, 100]}
          receiveShadow
        />
        <mesh
          name="Fan_Light_"
          geometry={nodes.Fan_Light_.geometry}
          material={materials["m1.002"]}
          position={[0, 451.32, -676.65]}
          scale={10.31}
          castShadow
        />

        {/* <mesh name="Sketchfab_model006" geometry={nodes.Sketchfab_model006.geometry} material={materials.Material__25} position={[-290.14, -327.71, -377.7]} castShadow  /> */}

        <mesh
          name="Sketchfab_model006"
          geometry={nodes.Sketchfab_model006.geometry}
          material={materials.Material__25}
          position={[-290.14, -327.71, -377.7]}
          castShadow
        >
          <PositionalAudio url="/Wating_Room.mp3" autoplay loop />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/jpbs/jpbs.glb");
